wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.6
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1767249121.999286
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 2
      - 13
      - 23
      4: 3.12.6
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
